PREFIX : <http://kg2025.unitn.it/trentino#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?name ?bus
WHERE {
  ?attraction a :NaturalAttraction ;
              :hasName ?name ;
              :hasNearbyBusStop ?bus .
}